#!/bin/sh
#
# This is [custom `pre-commit`](https://github.com/SwuduSusuwu/SusuLib/blob/preview/hooks/pre-commit):
# Produces `./tags` [for `vim`](../README.md#purposes), updates `./compile_commands.json` [for `clang-tidy`](../README.md#purposes), calls [sample `pre-commit` (which scans for non-ASCII filenames, conflict markers or whitespace errors)](../.git/hooks/pre-commit.sample)
GIT_ROOT="$(dirname "$(git rev-parse --git-dir)")/" # `git` does not set `${GIT_DIR}`, nor `${GIT_WORK_TREE}`
SUSUWU_INCLUDE_ERROR() { #/* Usage; `SUSUWU_INCLUDE_ERROR "<relative path>" "error message"` */
		echo "[$0: Error: \`GIT_WORK_TREE=${GIT_ROOT}\` \`\${GIT_WORK_TREE}${1}\` ${2}.]"; exit 1
}
SUSUWU_INCLUDE() { #/* Usage; `SUSUWU_INCLUDE "<relative path>"` */
	SUSUWU_INCLUDE_PATH=${1}; shift #/* So path is not included in source'd scripts `$@` and `$*`. */
	if [ ! -e "${GIT_ROOT}${SUSUWU_INCLUDE_PATH}" ]; then
		SUSUWU_INCLUDE_ERROR "${SUSUWU_INCLUDE_PATH}" "was not found"
	elif [ ! -x "${GIT_ROOT}${SUSUWU_INCLUDE_PATH}" ] || ! . "${GIT_ROOT}${SUSUWU_INCLUDE_PATH}"; then
		SUSUWU_INCLUDE_ERROR "${SUSUWU_INCLUDE_PATH}" "is not executable"
	fi
}
SUSUWU_INCLUDE "${GIT_ROOT}/sh/make.sh" || exit $? #/* SUSUWU_BUILD_CTAGS() SUSUWU_COMPILE_JSON_PATH_ SUSUWU_GITHUB_WORKSPACE_JSON() SUSUWU_IS_PREVIEW() */
SUSUWU_GITHUB_WORKSPACE_JSON && git add "${SUSUWU_COMPILE_JSON_PATH_}" #/* Replace `$(pwd)` with `${{ github.workspace }}` for `compile_commands.json` */

if SUSUWU_IS_PREVIEW; then #/* If `./tags` is tracked; */
	SUSUWU_BUILD_CTAGS 2>/dev/null && git add "${GIT_ROOT}/tags" #/* produce&add `./tags`. */
fi

git config core.whitespace -blank-at-eof # Prevents "new blank line at EOF."
. "$0.sample" # "An example hook script to verify what is about to be committed."

