#!/bin/sh
#
# This is [custom `prepare-commit-msg`](https://github.com/SwuduSusuwu/SusuLib/blob/preview/hooks/prepare-commit-msg):
# Produces `./tags` [for `vim`](../README.md#purposes), restores metadata to prevent "error: cannot rebase: You have unstaged changes.".
# TODO: to prevent [race conditions](https://wikipedia.org/wiki/Race_condition), execute more soon.
GIT_ROOT="$(dirname "$(git rev-parse --git-dir)")/" # `git` does not set `${GIT_DIR}`, nor `${GIT_WORK_TREE}`
SUSUWU_INCLUDE_ERROR() { #/* Usage; `SUSUWU_INCLUDE_ERROR "<relative path>" "error message"` */
	echo "[$0: Error: \`GIT_WORK_TREE=${GIT_ROOT}\` \`\${GIT_WORK_TREE}${1}\` ${2}.]"; exit 1
}
SUSUWU_INCLUDE() { #/* Usage; `SUSUWU_INCLUDE "<relative path>"` */
	SUSUWU_INCLUDE_PATH=${1}; shift #/* So path is not included in source'd scripts `$@` and `$*`. */
	if [ ! -e "${GIT_ROOT}${SUSUWU_INCLUDE_PATH}" ]; then
		SUSUWU_INCLUDE_ERROR "${SUSUWU_INCLUDE_PATH}" "was not found"
	elif [ ! -x "${GIT_ROOT}${SUSUWU_INCLUDE_PATH}" ] || ! . "${GIT_ROOT}${SUSUWU_INCLUDE_PATH}"; then
		SUSUWU_INCLUDE_ERROR "${SUSUWU_INCLUDE_PATH}" "is not executable"
	fi
}
SUSUWU_INCLUDE "${GIT_ROOT}/sh/make.sh" #/* SUSUWU_BUILD_CTAGS() SUSUWU_GITHUB_WORKSPACE_JSON() */ # . "${GIT_ROOT}/sh/Macros.sh" #/* SUSUWU_IS_PREVIEW() */
STATUS_CODE=$?
#git restore "${GIT_ROOT}/compile_commands.json" 2>/dev/null
SUSUWU_GITHUB_WORKSPACE_JSON #/* Replace `$(pwd)` with `${{ github.workspace }}` for `compile_commands.json` */
if SUSUWU_IS_PREVIEW; then #/* If `./tags` is tracked; */
	(SUSUWU_BUILD_CTAGS 2>/dev/null && git add "${GIT_ROOT}/tags") || (#/* produce&add `./tags`. */
		echo "$0: [Error]: Could not update \"${GIT_ROOT}/tags\"."
	)
fi
return ${STATUS_CODE}

